env:
  browser: true
  es2021: true
extends:
  - 'plugin:react/recommended'
  - standard
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules: {
  semi: ['error', 'always'],
  semi-style: ['error', 'last'],
  no-extra-semi: 'error',
  no-use-before-define: 'off',
  indent: ['error', 4],
}
